export const theme = {
    colors: {
        primary: '#0F172A',
        primarySoft: '#1E293B',
        active: '#0EA5E9',
        activeSoft: '#38BDF8',
        background: '#F8FAFC',
        surface: '#FFFFFF',
        text: '#0F172A',
        textMuted: '#64748B',
        textSubtle: '#94A3B8',
        success: '#16A34A',
        warning: '#F59E0B',
        danger: '#EF4444',
        border: '#E2E8F0',
        glass: 'rgba(255,255,255,0.65)',
        glassDark: 'rgba(15,23,42,0.7)',
    },
    radii: {
        xs: 8,
        sm: 12,
        md: 16,
        lg: 20,
        xl: 28,
        pill: 999,
    },
    spacing: {
        xs: 6,
        sm: 10,
        md: 16,
        lg: 20,
        xl: 28,
        xxl: 36,
    },
    shadow: {
        soft: {
            shadowColor: '#0F172A',
            shadowOffset: { width: 0, height: 8 },
            shadowOpacity: 0.1,
            shadowRadius: 16,
            elevation: 5,
        },
    },
    font: {
        display: 'Avenir Next',
        body: 'Avenir Next',
    },
};
