import { supabase } from '@/lib/supabase';

export type ContractData = {
    projectTitle: string;
    projectCity: string;
    budget: number;
    milestones: { title: string; amount: number; step_order: number }[];
    clientName?: string;
    providerName?: string;
    clientSignedAt?: string;
    providerSignedAt?: string;
};

/**
 * Generate contract HTML for PDF. Signatures can be data URLs or text.
 */
export function getContractHtml(data: ContractData, clientSignatureDataUrl?: string | null, providerSignatureDataUrl?: string | null): string {
    const rows = data.milestones
        .map((m) => `<tr><td>${m.step_order}</td><td>${escapeHtml(m.title)}</td><td>${m.amount.toLocaleString()} CFA</td></tr>`)
        .join('');
    const clientSig = clientSignatureDataUrl
        ? `<img src="${clientSignatureDataUrl}" alt="Client" style="max-width:180px;height:48px;object-fit:contain;" />`
        : (data.clientSignedAt ? `<p>Signed electronically ${new Date(data.clientSignedAt).toLocaleString()}</p>` : '');
    const providerSig = providerSignatureDataUrl
        ? `<img src="${providerSignatureDataUrl}" alt="Provider" style="max-width:180px;height:48px;object-fit:contain;" />`
        : (data.providerSignedAt ? `<p>Signed electronically ${new Date(data.providerSignedAt).toLocaleString()}</p>` : '');
    return `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><title>Contract</title>
<style>
  body { font-family: system-ui, sans-serif; padding: 24px; color: #0F172A; max-width: 600px; margin: 0 auto; }
  .brand { font-weight: 800; color: #0EA5E9; margin-bottom: 24px; }
  h1 { font-size: 20px; margin: 0 0 16px 0; }
  table { width: 100%; border-collapse: collapse; margin: 16px 0; }
  th, td { border: 1px solid #E2E8F0; padding: 10px; text-align: left; }
  th { background: #F8FAFC; font-weight: 700; }
  .signatures { display: flex; justify-content: space-between; margin-top: 32px; gap: 24px; }
  .sig-block { flex: 1; border: 1px solid #E2E8F0; padding: 12px; border-radius: 8px; }
  .sig-label { font-size: 11px; color: #64748B; text-transform: uppercase; margin-bottom: 8px; }
  .footer { margin-top: 32px; font-size: 11px; color: #94A3B8; }
</style>
</head>
<body>
  <div class="brand">DIASPORA BRIDGE – CONSTRUCTION AGREEMENT</div>
  <h1>${escapeHtml(data.projectTitle)}</h1>
  <p><strong>Location:</strong> ${escapeHtml(data.projectCity)}</p>
  <p><strong>Total budget:</strong> ${data.budget.toLocaleString()} CFA</p>
  <h2>Milestones &amp; Payments</h2>
  <table>
    <thead><tr><th>#</th><th>Phase</th><th>Amount</th></tr></thead>
    <tbody>${rows}</tbody>
  </table>
  <p>Funds are held in escrow and released per milestone upon client approval.</p>
  <div class="signatures">
    <div class="sig-block">
      <div class="sig-label">Client</div>
      ${clientSig}
    </div>
    <div class="sig-block">
      <div class="sig-label">Provider</div>
      ${providerSig}
    </div>
  </div>
  <div class="footer">Generated by Diaspora Bridge. This is a computer-generated contract.</div>
</body>
</html>
  `.trim();
}

function escapeHtml(s: string): string {
    return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

/**
 * Upload a local PDF file (by URI) to Supabase storage and return public URL.
 * Caller is responsible for generating the PDF (e.g. with expo-print) so this file has no expo-print dependency.
 */
export async function uploadContractPdfFromUri(projectId: string, localPdfUri: string): Promise<string> {
    const response = await fetch(localPdfUri);
    const blob = await response.blob();
    const path = `contracts/${projectId}_${Date.now()}.pdf`;
    const { error } = await supabase.storage.from('contracts').upload(path, blob, { contentType: 'application/pdf' });
    if (error) throw error;
    const { data } = supabase.storage.from('contracts').getPublicUrl(path);
    return data.publicUrl;
}
